# Generated by Django 5.2.4 on 2025-08-01 09:49

import morapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_report_reportcategory_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=morapp.utils.generate_order_number, max_length=16, unique=True),
        ),
    ]
