# Generated by Django 5.2.4 on 2025-08-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_report_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
